### ISSUE TITLE
Developer setup not working

### ISSUE THREAD

**Issue by magdalenafuentes** [soundata/soundata#10]
I tried to set up a new environment following [this instructions](https://mirdata.readthedocs.io/en/latest/source/contributing.html?highlight=black#installing-mirdata-for-development-purposes) and the `pip install .[tests]` didn't work for me. Double check if that's the case with other people and if so fix it.

**Comment by justinsalamon** [comment]
Cross referencing with #1

**Comment by magdalenafuentes** [comment]
Coming back to this, I tried it in different machines and sometimes it works and sometimes it doesn't. Also a colleague of mine told me for him it wasn't working as it is, but `".[tests]"` did

**Comment by justinsalamon** [comment]
Any luck identifying the source of error?
