### ISSUE TITLE
"latest" API docs appear to be outdated

### ISSUE THREAD

**Issue by jtcramer** [soundata/soundata#107]
The [stable docs](https://soundata.readthedocs.io/en/stable/source/quick_reference.html) appear to have all of the datasets in the repo, but the [latest ](https://soundata.readthedocs.io/en/latest/source/quick_reference.html) seem to be missing some of those datasets for some reason.

**Comment by harshpalan** [comment]
There was a mismatch in the branch name in readthedocs which caused this issue. It has been updated now.
