### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by samansaeedi102** [soundata/soundata#109]
dataset = soundata.initialize('urbansound8k')
dataset.download()  # download the dataset
dataset.validate()  # validate that all the expected files are there

soundata failed to download the dataset from https://zenodo.org/record/1203745/files/UrbanSound8K.tar.gz?download=1!
                            Please try again in a few minutes.
                            If this error persists, please raise an issue at
                            https://github.com/soundata/soundata,
                            and tag it with 'broken-link'.

**Comment by harshpalan** [comment]
Hi @samansaeedi102, thanks for reporting an issue, but this looks like an intermittent issue. Please check again and let us know. 

Here is my output for reference: 
```
>>> import soundata
>>> dataset = soundata.initialize('urbansound8k')
>>> dataset.download()
INFO: Downloading ['all'] to /tmp\sound_datasets\urbansound8k
INFO: [all] downloading UrbanSound8K.tar.gz
5.61GB [15:08, 6.63MB/s]
>>> dataset.validate()
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 76.80it/s] 
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8732/8732 [01:28<00:00, 98.33it/s] 
INFO: Success: the dataset is complete and all files are valid.
INFO: --------------------
({'metadata': {}, 'clips': {}}, {'metadata': {}, 'clips': {}})
```
