### ISSUE TITLE
Black formatting not so clear in the tutorial

### ISSUE THREAD

**Issue by magdalenafuentes** [soundata/soundata#11]
Shouldn't it be install at the same time that other tests in [this instructions](https://mirdata.readthedocs.io/en/latest/source/contributing.html?highlight=black#installing-mirdata-for-development-purposes)?

**Comment by justinsalamon** [comment]
Yes, cf. #1 #10

**Comment by magdalenafuentes** [comment]
Should be addressed by #26

**Comment by magdalenafuentes** [comment]
Also should we recommend a version? it seems that different versions give different results and the tests break because of it

**Comment by magdalenafuentes** [comment]
Done in #26
