### ISSUE TITLE
ERROR: Could not build wheels for numpy

### ISSUE THREAD

**Issue by loijilai** [soundata/soundata#121]
Hi, I got error during installation by `pip install soundata`

The error message:
"ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects"

My python version is 3.10.11 and numpy version is 1.25.0.
Tested in conda virtual environment with WSL2.

**Comment by loijilai** [comment]
I found that in the output message of the shell during installation, the numpy version used is 1.20.0, which may cause the error. Is there any way to use other numpy version for installing the package?

<img width="350" alt="螢幕擷取畫面 2023-07-10 201129" src="https://github.com/soundata/soundata/assets/52855315/d1e4a2dc-e18e-4c2a-8a7c-c1bd5a186347">

**Comment by harshpalan** [comment]
Hi @loijilai. Thanks for reporting this issue. We are currently in the process of updating the library to support Python 3.10 and above. It should be available soon. You can track the updates in [PR 119](https://github.com/soundata/soundata/pull/119).

**Comment by avinashtarale** [comment]
hi @loijilai were you able to install the soundata? I want to access the dataset, but I am also getting same error for bumpy. I am using bumpy = 1.25 version.

**Comment by loijilai** [comment]
@avinashtarale no I haven't solved the problem.

**Comment by iranroman** [comment]
I'm facing the same issue.

**Comment by avinashtarale** [comment]
@iranroman , @loijilai I did manage to download the souddata using python 3.8 and numpy 1.20.0 version. 
If you just want the audio set, you can download it first and later update the python and numpy with venv.
