### ISSUE TITLE
Separate indexes from Python package

### ISSUE THREAD

**Issue by hagenw** [soundata/soundata#155]
At the moment the indexes of all datasets available with `soundata` are all bundled with the Python package:

https://github.com/soundata/soundata/blob/62fdaa6e792601c0183766b6bf50574a8d0131db/setup.py#L19

This works ok with the [list of currently included datasets](https://soundata.readthedocs.io/en/latest/source/quick_reference.html), which results in a size of 108M of `soundata/datasets/indexes/`. The largest included dataset is `TAU Urban Acoustic Scenes 2022 Mobile` with 349150 audio clips, resulting in 97 h of audio.

But as soon as a bunch of larger datasets would be included, e.g. [IMDA National Speech Corpus (NSC)]() which has >5,000,000 of clips and >5,000 h of audio, the size of the `indexes` folder and hence the Python package will become unreasonable large.

A better solution might be to have a central place to store the index files from which they can then be downloaded and locally cached by `soundata`.

**Comment by guillemcortes** [comment]
Closing this since it has been addressed in #169
