### ISSUE TITLE
Add a CONTRIBUTING file to the root of the repository

### ISSUE THREAD

**Issue by hagenw** [soundata/soundata#161]
To make it easier to find the documentation on contributing, I would recommend to add a `CONTRIBUTING.rst` to the root of the repo.
It's content can then simply be included inside `docs/source/contributing.rst`, e.g.

```rst
.. include:: ../../CONTRIBUTING.rst
```

**Comment by genisplaja** [comment]
Dear @hagenw, thank you for your suggestion. We've tested this one, but GitHub is not [rendering the notes properly](https://github.com/github/markup/issues/1682) and it doesn't properly import files as sphinx does, therefore, to enchance readability, we should be creating a standalone contribution file for the root folder, and another standalone file for the docs, and we believe that this may be a bit overkill. 

In fact, in the `README.md` file we are linking directly the contribution guidelines. Maybe we would propose to move this up and highlight it, for users to find it quickly. Does that sound good? Thanks!

**Comment by hagenw** [comment]
Yes, good point.

An alternative solution would be to move parts from the "Contributing" section to their own top-level section, but I think the current structure makes sense, and I would propose to stay with it. 

So maybe add a short sentence to the top of the README as well, e.g. inside

![image](https://github.com/soundata/soundata/assets/173624/7d589063-bd55-426f-88cf-e843966afd6e)

I also like that you have only two lines there, so maybe try to fit it in the first line? E.g.

> Python library for downloading & working with sound datasets. Check the [API documentation]() and [contribute]() datasets.

**Comment by hagenw** [comment]
This was solved by #165
