### ISSUE TITLE
Include the command how to build documentation locally

### ISSUE THREAD

**Issue by hagenw** [soundata/soundata#162]
At the moment it is discussed in the contribution documentation, that the documentation is automatically build for each pull request, which is a very nice feature. Nonetheless, I would also recommend to describe how to build the documentation locally.

For example, I tried to build it with running:
```bash
$ python -m sphinx docs/ build/html -b html
```
The build succeeded, but I got 134 warnings. So I'm not sure if I should have done it differently?

**Comment by genisplaja** [comment]
No, you are doing it right. It could actually be done running `make clean html` also. The warnings are produced by formatting issues in the docstrings of the data loaders. I've been fixing them all, and wrote down in the documentation some indications to prevent these warnings. Thanks for bringing this up!

**Comment by hagenw** [comment]
I realized, I overlooked the documentation on how to build the docs before. Maybe it is not optimal, that the documentation is discussed at two different places in contributing, namely "Writing a new dataset loader > 4. Submit your loader > Docs" and under "Documentation".

I can confirm that with #165 I don't get any warnings when building the docs locally.

**Comment by guillemcortes** [comment]
You're right, we took note of this for future review. Thanks for the heads up!

**Comment by guillemcortes** [comment]
Closing this issue, marking it as resolved
