### ISSUE TITLE
ModuleNotFoundError: No module named 'pydub'

### ISSUE THREAD

**Issue by ccibeekeoc42** [soundata/soundata#177]
Over the past 18 hours, I have been getting the error below anytime I try to download a dataset. Even after I manually fix it by installing the requested dependency, it causes a different error (also recorded below). And when I fix the second errr, it causes a third and on and on....

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-3-9254bc38efaa>](https://localhost:8080/#) in <cell line: 1>()
----> 1 dataset = soundata.initialize('urbansound8k')
      2 dataset.download()                                                              #download the dataset
      3 dataset.validate()                                                              #validate the dataset

10 frames
[/usr/local/lib/python3.10/dist-packages/soundata/display_plot_utils.py](https://localhost:8080/#) in <module>
      1 # Audio Processing and Playback
----> 2 from pydub import AudioSegment  # For manipulating audio files
      3 from pydub.playback import play  # For playing audio files
      4 import simpleaudio as sa  # Alternative library for audio playback
      5 import librosa  # For advanced audio analysis

ModuleNotFoundError: No module named 'pydub'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-6-9254bc38efaa>](https://localhost:8080/#) in <cell line: 1>()
----> 1 dataset = soundata.initialize('urbansound8k')
      2 dataset.download()                                                              #download the dataset
      3 dataset.validate()                                                              #validate the dataset

10 frames
[/usr/local/lib/python3.10/dist-packages/soundata/display_plot_utils.py](https://localhost:8080/#) in <module>
      2 from pydub import AudioSegment  # For manipulating audio files
      3 from pydub.playback import play  # For playing audio files
----> 4 import simpleaudio as sa  # Alternative library for audio playback
      5 import librosa  # For advanced audio analysis
      6 

ModuleNotFoundError: No module named 'simpleaudio'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

**Comment by genisplaja** [comment]
Hey @ccibeekeoc42. Thanks for raising this problem. This is fixed in the latest `soundata` release we just made (v1.0.1). Please update and you should be able to initialize the loaders with no problem. Thanks!
