### ISSUE TITLE
Multiple data-loaders libraries vs. one that fits them all

### ISSUE THREAD

**Issue by magdalenafuentes** [soundata/soundata#2]
There's an ongoing discussion with @nkundiushuti in the context of `mirdata` of whether we should have two separate repositories (i.e. `mirdata` and `dcasedata`) for common loaders or if we should have the loaders in the same place. I open the issue here so we brainstorm the advantages of both approaches.

I think it makes sense to have to separate repos for the following reasons: 1) the repos should have independent timelines and priorities because they focus in different communities; 2) I think the message is clearer if we keep all MIR things in one repo and dcase stuff in other,  for related communities to relate and contribute; 3) we can make the repos more specific to their needs (e.g. coupling in a nice way `dcasesdata` with `dcase_models`). 

The main disadvantage we discussed is that at some point repos will diverge, and we won't be able to benefit from each other's work easily. This is a bit inconvenient if we consider that me, @nkundiushuti and other MTG folks might contribute to both repositories in the future. Are there any ideas on how to help with this?

**Comment by justinsalamon** [comment]
This is a good topic of discussion and you raise many good points. Overall, I agree with you about the benefits of having two separate repositories, for all the reasons you've mentioned. 

I also think there's a serious risk of letting "perfect" be the enemy of "good", in this case perfect being striving for a single unified library, which would prevent us from making meaningful progress on this library and would slow down progress on `mirdata` as well.

My humble suggestion would be for us to start as we have, and evolve this library based on user needs. If the library becomes popular and users ask if we can unify it with `mirdata`, we can consider it then. Right now it seems like a heavy engineering lift for something we're not even sure there's demand for, which would also muddy the definition of `mirdata`.

Thoughts?

**Comment by magdalenafuentes** [comment]
Agree 100%

Also, we're engineering a few heavy API changes in `mirdata` which simplifie code a lot and fix issues on big datasets. IMO we should get this repo sync to that and then each project should move independently

**Comment by justinsalamon** [comment]
Sounds good to me.

Perhaps we can close this issue out (for now, we can always re-open if need be) - do you want to open a new issue to highlight the changes in `mirdata` and discuss a plan for porting these changes over here?

**Comment by nkundiushuti** [comment]
hey! we plan to put the loader for freesound dataset somewhere so I have a few questions. for us it would be easier if freesound would sit in mirdata. I don't think we should hurry to have a new repo just as a "politics" decision (what would be the politics behind this decision? another paper? what's the point of having 10 tools for doing the same thing with slight variations?). in our case, we decided to use mirdata for the datasets in MTG despite the "politics". we think that a joint effort is better for sustainability. there is a higher chance this repo would be maintained in a few years for now. in addition, we think that mirdata could benefit from "meaningful progress", meaning that our contributions would change mirdata for better. I think it can happen the same with the environmental sounds. I think we can achieve something great together! :) 

So, the questions: 

what are the particular limitations of mirdata that you are trying to address with a new repository? for instance, is the Track object accompanied by annotations not fit for environmental sounds?

and maybe mirdata could take advantage of the "heavy API changes" ? for instance coupling it with dcase_models would involve changes that would render it incompatible with mirdata? which are these changes?

**Comment by pzinemanas** [comment]
Hi! I agree with Magda and Justin. Maybe I'm still an outsider, but I don't see the political issue. I think that the main motivation is to keep these tools useful for the communities. In this sense, the DCASE community is now independent from the MIR community. There are many people, groups and companies that work on environmental sounds and not in music-related problems. These people could collaborate on this new repo and I'm not sure that it would be easy for them (us) to collaborate in this 'all-inclusive' tool. 

Besides that, the problems related to the DCASE community are growing and diverging from the typical ones. I suppose the same is happening in the MIR community. So I think separate repositories can follow these changes better. In the end, each community focuses on its problems. 

However, we can do our best to keep envsoundata from diverging from mirdata so that people can collaborate on both repositories. In the future, we might even create a common platform for both libraries if this helps.

**Comment by magdalenafuentes** [comment]
I see it as a practical issue rather than a political one. Keeping the two repositories separated will allow for moving faster in each project independently and for more flexibility to address field-specific idiosyncrasies IMO. At least it is what makes sense to me now. We can always make changes in the future if we conclude something else is better.

When I mentioned the heavy changes I meant the changes in `mirdata` reflected here and not the other way around.

**Comment by rabitt** [comment]
> My humble suggestion would be for us to start as we have, and evolve this library based on user needs. If the library becomes popular and users ask if we can unify it with mirdata, we can consider it then. Right now it seems like a heavy engineering lift for something we're not even sure there's demand for, which would also muddy the definition of mirdata.

**Comment by justinsalamon** [comment]
Thanks everyone, sounds like we're mostly in agreement so let's move forward with the current plan of two separate repos.

@nkundiushuti I appreciate the points you have raised, but I believe the pros of having 2 repos outweigh the cons here.

Closing this one out. @magdalenafuentes let's open a separate issue about pulling the upstream improvements from mirdata over here. Cheers everyone!
