### ISSUE TITLE
How are we gonna handle multiple annotators ?

### ISSUE THREAD

**Issue by magdalenafuentes** [soundata/soundata#31]
I started writing the loader of `sonyc_ust` which has multiple annotators for each file, and binary labels for a set of classes. I was wondering how do we wanna handle this. I have some ideas but I'm happy to hear what others think:

For the binary labels, since the dataset has a defined taxonomy, I'm gonna get the vector `[0, 1, 0, ... ,1]` corresponding to activations of the different classes `[class_1, class_2, ... , class_N]` from each clip into tags, so the clip will have a list of only the classes present in that clip (e.g. `[class_2, class_N]`. This allows to explore clip-wise metadata easy. For exploring the big picture of the dataset, I refer to #22.

For handling multiple annotators, I see two possible solutions:

Right now `clips.tags = annotations.Tags` which internally has a list of labels and a list of confidence values. 

1) One option is to return a list of `annotations.Tags` and have a separated property for the annotator IDs, ordered in the same way:

```
clip.tags = [annotations.Tags, annotations.Tags, ... ]
clip.annotators = [annotator_1, annotator_2, ... ]  # these are str
```
Good: the datasets will always have the same property `tags`. Bad: `tags` is used in different ways in different datasets and is not so clear the link between annotators and their annotations.

2) We introduce a `muti_annotator` annotation type or property with `tuples` matching annotator ID and annotation:

```
clip.multi_annotator = [(annotation, annotator_ID), (annotation, annotator_ID), ...]
```
In this case `annotation` is `annotations.Tags`.

Good: it's very clear the dataset has a ground truth with multiple annotators. Bad: the annotation type gets a bit buried down in the code, so we have to be super clear in the docs or try to make it very intuitive somehow.

Thoughts? @justinsalamon @mrocamora @pzinemanas @mcartwright

**Comment by mcartwright** [comment]
Yeah, I think the new type would be better since it's clearer what's going on. I fear without being explicit people might misinterpret the data before digging into the specifics.

**Comment by mcartwright** [comment]
Eventually it would be great to add in some built-in aggregators so the code for those processes are standardized for datasets with multiple annotators per example. (if this is of interest to soundata folks, i could potentially contribute here. happy to discuss more...)

**Comment by magdalenafuentes** [comment]
Yes, I agree with the aggregators, is related to #22. Definitely makes sense for you to give input/contribute!

**Comment by justinsalamon** [comment]
Thanks for the great discussion.

I agree that it would be better to have a new structure here rather than overloading `clip.tags`, i.e. @magdalenafuentes 's option 2 over option 1.

We should think this carefully to come up with a good API for this. For example, we could:
1. Have 1 structure for multiple annotations, like in the example for option 2, that can hold either Tags or Events annotations
2. Alternatively, we could have `multi_tags` and `multi_events` for each of the two annotation types

Option 1 has the benefit of a structure that's agnostic of annotation type, and doesn't have to change if we add more annotation types in the future (though, unlike MIR, I don't expect too many new types). The down side is that it's harder to validate (need to check for all allowed annotation types) and hides the actual annotation type inside something that is type agnostic.

I can see pros and cons to both, and there are probably other option as well I'm not thinking of. Thoughts?

**Comment by justinsalamon** [comment]
...and I just thought of a 3rd option :) 

We could, alternatively, use the **same** structure both for single and multi annotations. In this case a single annotation would just be a special case of of a multi annotation that has just 1 annotator.

In this case we could directly change the semantics of `clip.tags` and `clip.events` such that they always contain a list. This would have the advantage of providing a single API for both single and multi-annotated data. The disadvantage however would be that it would make the syntax more cumbersome, as `clip.tags` would become something like `clip.tags[0]`. Unless we add some syntactic magic such that `clip.tags` points to `clip.tags[0]`. Then for datasets with just 1 annotator it would appear transparent to the user (`clip.tags` and `clip.events` would behave as they do now), and with multiple annotators tou could index into `clip.tags[idx]`.

Just an idea...

**Comment by magdalenafuentes** [comment]
I was thinking of a `type agnostic` solution (i.e. 1. have one structure for multiple annotations). I think is cleaner and we can test it to be consistent within each loader (similarly to how we test annotations now, that we check expected type). Also we document one annotation structure only instead of duplicating docs for all of them.

I like the 3rd option in the sense that unifies things, but I'm afraid it will be obscure for most loaders which have single annotators (e.g.  something like `return load_tags[0]` each time?). Since we can move to option 3 any time without breaking the API, I'm more inclined right now to go for `option 1` and move to `option 3` if it makes sense as the library grows

**Comment by justinsalamon** [comment]
@magdalenafuentes that sounds reasonable to me, but... imagine a clip that has both multiple tag annotations and multiple events annotations. If we store all of them in the same `multi_annotator` field, we'd be mixing annotation types, which is different in terms of API design to having separate `clip.tags` and `clip.events`.

Now that I think about it, this makes the design of option 1 a little problematic, no?

**Comment by magdalenafuentes** [comment]
Yeah, I see your point. What about then using the `clip.tags` and `clip.events` but returning a `Multiple_Annotators` object?

Good: it would be flexible and we can easily test and extend to other annotation types, plus still very clear when we have multiple annotators. Bad: in some cases `clip.tags` will be type `annotation.Tags`, and others will be `annotations.Multi_Annotator` type.

I'm ok with this, I think it already happens that some datasets have `clip`, others will have `clip_group` and so on, so it's within the variability I'm comfortable with :)

What are your thoughts?

**Comment by justinsalamon** [comment]
@magdalenafuentes IIUC that's the same as my option 3, no?

> We could, alternatively, use the same structure both for single and multi annotations. In this case a single annotation would just be a special case of of a multi annotation that has just 1 annotator.

> In this case we could directly change the semantics of clip.tags and clip.events such that they always contain a list. This would have the advantage of providing a single API for both single and multi-annotated data. The disadvantage however would be that it would make the syntax more cumbersome, as clip.tags would become something like clip.tags[0]. Unless we add some syntactic magic such that clip.tags points to clip.tags[0]. Then for datasets with just 1 annotator it would appear transparent to the user (clip.tags and clip.events would behave as they do now), and with multiple annotators tou could index into clip.tags[idx].

As you propose for datasets with multiple annotators we return some form of `multi_annotator` object, and for datasets with just one annotator we directly return the annotation object (Tags or Events). Under the hood we could implement this such that even just 1 annotation is stored in the multi object, but the clip knows if it has mutiple annotations or not (could be a clip attribute maybe?) and then we you call `clip.tags` you either get back the annotation list (for multi) or the annotation object directly if there's only 1 annotation.

The alternative would be to always return the annotation list (even for 1 annotation), but I think most datasets only have 1 annotation so this would add a lot of unnecessary indexing to user the code.

thoughts?

**Comment by magdalenafuentes** [comment]
Yes! It's basically your `option 3` but as you mention now I also prefer not to return always a list, instead return different things depending on the case. 

We agree that the user interface should be simple, so if only one annotation is available you directly get `Tags` or `Events`. 
 The remaining question is what is the clearer thing to do from a contributor point of view. Is it to always have a `general annotation` type where you have to indicate `annotator_id`, though probably for datasets with only one annotator that question will be strange? Or to have people use `tags` and `events` and only redirect them to this new annotations type when they have multiple annotators?

**Comment by justinsalamon** [comment]
OK cool!

I would opt for sticking with the current simple format for single annotator, i.e. when there's just one annotation you don't need to indicate speaker ID or anything, everything works as it does now and is transparent to the user.

When there are multiple annotations, then we need to decide what structure we return to the user. It could be:
* A list of tuples `[(annotation1, annotator_id1), (annotation2, annotator_id2), ...]`
* Two lists: `[annotation1, annotation2, ...], [annotator_id1, annotator_id2, ...]`
* Some new object that we defined e.g. `MultiAnnotation` that internally stores the annotations in one of the two previous formats

Between the first two formats I think the second one (two separate lists) will be easier to work with compared to a list of tuples (tuples are always a pain). 

In terms of the third option, I'd only go there if we feel it adds value. For example, 
* it could implement annotation aggregation function as part of its API - `clip.tags.aggregate(method="majority_vote")` and `clip.events.aggregate(method="majority_vote")`. 
* However, those aggregation functions could also be implemented as part of the `Clip` API, such that you would call something like `clip.aggregate_tags(method="majority_vote")` and `clip.aggregate_events(method="majority_vote")` 
* Or even as part of the `Tags` and `Events` APIs, e.g., `from soundata.annotations import aggregate; aggregate(clip.tags); aggregate(clips.events)`.

@magdalenafuentes @mcartwright wacha think?

**Comment by magdalenafuentes** [comment]
@justinsalamon @mcartwright I drafted an idea in #46 for you to take a look. Let me know what do you think!

**Comment by justinsalamon** [comment]
@magdalenafuentes looks great, I suggest we use `MultiAnnotation` as the class name, but otherwise lgtm!
