### ISSUE TITLE
scripts/print_track_docstring.py does not exist

### ISSUE THREAD

**Issue by iranroman** [soundata/soundata#56]
The file `scripts/print_track_docstring.py` is not present and is referenced in the contributing guidelines. 

Solution: include the file or revise guidelines to not reference it.

**Comment by justinsalamon** [comment]
Thanks @iranroman - the contributing guidelines have not been updated yet for `soundata` - please hang tight, we're hoping to get them up to seed real soon

cc @magdalenafuentes

**Comment by magdalenafuentes** [comment]
Addressed in #26
