### ISSUE TITLE
ESC-50 file may be corrupted

### ISSUE THREAD

**Issue by sripathisridhar** [soundata/soundata#67]
Hello, it looks like there might an issue with the ESC-50 file checksum downloaded by the loader. This happened multiple times on different days.

OSError: /Users/usr/sound_datasets/esc50/ESC-50-master.zip has an MD5 checksum (7771e4b9d86d0945acce719c7a59305a) differing from expected (70aba3bada37d2674b8f6cd5afd5f065), file may be corrupted.

**Comment by magdalenafuentes** [comment]
Hi @sripathisridhar! Thanks for reporting this, can you share the code you're running so I can reproduce the error? Is it happening when you download? Have you tried downloading with `force_overwrite=True`?

**Comment by magdalenafuentes** [comment]
Hi @sripathisridhar, I could reproduce your error. I'm looking into it now. Thanks for opening the issue!
