### ISSUE TITLE
Documentation link not updated to v0.1.1

### ISSUE THREAD

**Issue by kwatcharasupat** [soundata/soundata#96]
The default documentation link at https://soundata.readthedocs.io/en/latest is still at v0.1.0.

(The stable build docs https://soundata.readthedocs.io/en/stable is up to date at v0.1.1)

**Comment by kwatcharasupat** [comment]
Bumping this as it is not fixed as of v0.1.2.

**Comment by harshpalan** [comment]
There was a mismatch in the branch name in readthedocs which caused this issue. It has been updated now.
