### ISSUE TITLE
possible module missing in the requirements?

### ISSUE THREAD

**Issue by nkundiushuti** [soundata/soundata#97]
I installed soundata with pip and when initializing a dataset, I get this error. It is solved by installing typing_extensions with pip. 

~/miniconda3/envs/mirdata/lib/python3.7/site-packages/soundata/jams_utils.py in <module>
      4 import os
      5 from typing import Callable, List
----> 6 from typing_extensions import ParamSpecKwargs
      7 
      8 import jams

ModuleNotFoundError: No module named 'typing_extensions'

**Comment by magdalenafuentes** [comment]
Bumping this because I'm getting the same error
